servers:
- url: http://localhost:5000
  description: Development server
- url: http://localhost:5000
  description: Development server
paths:
  /alive:
    get:
      summary: Service Health Method
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
        '424':
          description: Failed dependency response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
        '503':
          description: Service unavailable response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /v1/event/{event_type}:
    get:
      summary: List event
      parameters:
      - in: path
        name: event_type
        description: Event type
        required: true
        schema:
          type: string
          example: ocoren-event
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventListResponse'
        4xx:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventListErrorResponse'
    post:
      summary: Create event
      parameters:
      - in: path
        name: event_type
        description: Event type
        required: true
        schema:
          type: string
          example: ocoren-event
      requestBody:
        description: Event to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventCreateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventCreateResponse'
        4xx:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventCreateErrorResponse'
info:
  title: template-serverless-lambda-python-lambda-api
  version: 1.0.1
openapi: 3.0.2
components:
  schemas:
    Entry:
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
            example: db
        duration:
          type: string
          example: '0:00:00.013737'
        status:
          type: string
          example: healthy
    EntryData:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Entry'
    HealthCheck:
      type: object
      properties:
        entries:
          $ref: '#/components/schemas/EntryData'
        total_duration:
          type: string
          example: '0:00:00.013737'
        status:
          type: string
          example: healthy
    Link:
      type: object
      properties:
        method:
          type: string
        href:
          type: string
        rel:
          type: string
    RequestControl:
      type: object
      properties:
        count:
          type: integer
        total:
          type: integer
        offset:
          type: integer
        limit:
          type: integer
      required:
      - limit
    Meta:
      type: object
      properties:
        last:
          type: string
          format: url
        next:
          type: string
          format: url
        href:
          type: string
          format: url
        first:
          type: string
          format: url
        previous:
          type: string
          format: url
    Event:
      type: object
      properties:
        hash:
          type: string
          example: 406cce9743906f7b8d7dd5d5c5d8c95d820eeefd72a3a554a4a726d022d8fa19
        date:
          type: string
          format: date-time
          example: '2021-05-03T19:41:36.315842-03:00'
        type:
          type: string
        data:
          type: object
    EventListResponse:
      type: object
      properties:
        label:
          type: string
          example: common.success
        message:
          type: string
          example: Success
        success:
          type: boolean
          example: true
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        control:
          $ref: '#/components/schemas/RequestControl'
        meta:
          $ref: '#/components/schemas/Meta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        code:
          type: integer
          example: 1
        params:
          type: array
          items:
            type: string
      required:
      - code
    EventListErrorResponse:
      type: object
      properties:
        trace:
          type: string
        details:
          type: string
        label:
          type: string
          example: common.error.internal_server_error
        message:
          type: string
          example: Internal Server Error
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 7
        params:
          type: array
          items:
            type: string
      required:
      - code
    EventCreateRequest:
      type: object
      properties:
        pedido:
          type: string
          example: Z1223321
        ocor:
          type: string
          example: MOTIVO DO CANCELAMENTO
        origem:
          type: string
          example: SAC/EAGLE
        chavenfe:
          type: string
          example: '32210206107255000134550010001712551245826554'
    EventCreateResponse:
      type: object
      properties:
        label:
          type: string
          example: common.event_registered_with_success
        result:
          type: boolean
          example: true
        message:
          type: string
          example: Event registered with success
        code:
          type: integer
          example: 102
        event_hash:
          type: string
          example: c82bf3ee20dd2f4ae7109e52d313a3190f1a85ba3362c54d3eb6257bd0c4d69d
        params:
          type: array
          items:
            type: string
    EventCreateErrorResponse:
      type: object
      properties:
        label:
          type: string
          example: common.error.event_type_unknown_error
        result:
          type: boolean
          example: false
        message:
          type: string
          example: 'Event type unknown: (%s)'
        code:
          type: integer
          example: 105
        event_hash:
          type: string
          example: null
        params:
          type: array
          items:
            type: string
